flags:
  wai-cli: { tls: false }
packages:
  - '.'
extra-deps:
  - socket-activation-0.1.0.2
  # - aeson-1.5.6.0
  # - aws-lambda-haskell-runtime-4.1.1
  - github: nomeata/aws-lambda-haskell-runtime
    commit: fa19268282a5afff7aa0ba8babc723d835bed4f1 # aeson-2.0
  - aws-lambda-haskell-runtime-wai-2.0.2
  - xml-lens-0.3.1
resolver: lts-19.28
