flags: {}
packages:
  - '.'
  - location:
      git: https://codeberg.org/valpackett/haskell-socket-activation.git
      commit: c67f50d80e4b83515e88672cbd689d4383710b23
    extra-dep: true
resolver: lts-7.14
